// Dependencies
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

// Components
import ProductCard from './components/ProductCard'
import Contact from './components/Contact'
import NavbarMobile from './components/NavbarMobile'

// Styles/Assets
import logo from '../assets/images/Ver_Logo_01.png'
import styles from '../styles/HomePage.module.scss'

// Other
import { constants } from '../utils/constants'

const {about, aboutText, portfolio} = constants

export default function Home() {

  const [navMobile, setNavMobile] = useState(false)

  const toggleNavbar = () => {
    return setNavMobile(prevState => !prevState)
  }

  return (
    <div >
      <Head>
        <title>Lifely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className={styles.homeBannerContainer}>

          <Image src={logo} alt="Lifely Logo"
          width={625} height={351} 
          />

          <div className={styles.navbarMobile}>
            <button onClick={() => toggleNavbar()}>X</button>
          </div>
        
        </div>

        <div>
          {navMobile ? <NavbarMobile/> : null }
        </div>

        <div className={styles.contentContainer}>
          <div >
            <h1>{about}</h1>
          <p>{aboutText}</p>
          </div>

          <div>
            <h1>
              {portfolio}
            </h1>
            <div className={styles.cardsContainer}>

            <ProductCard/>
            <ProductCard/>

            </div>
          </div>


        </div>

        <Contact/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
