// Dependencies
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

// Components
import Portfolio from './components/Portfolio'
import Contact from './components/Contact'
import NavbarMobile from './components/NavbarMobile'

// Styles/Assets
import logo from '../assets/images/Ver_Logo_01.png'
import navicon from '../assets/images/navicon.png'
import styles from '../styles/HomePage.module.scss'

// Other
import About from './components/About'

export default function Home() {

  const [navMobile, setNavMobile] = useState(false)

  const toggleNavbar = () => {
    return setNavMobile(prevState => !prevState)
  }

  return (
    <div >
      <Head>
        <title>Lifely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {/* Navbar Container */}
        <div className={styles.navbarContainer}>

          <Image src={logo} alt="Lifely Logo"
          width={104} height={58.5} 
          />

          <div className={styles.navbarMobile}>
            <button onClick={() => toggleNavbar()}>
              <Image src={navicon} alt="Nav Icon" width={30} height={30} />
            </button>
          </div>
        
        </div>

        <div>
          {navMobile ? <NavbarMobile/> : null }
        </div>

        
        
        <About/>

        <Portfolio/>

        <Contact/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
